export const LEGACY_SHELL_SCOPE = Object.freeze({
  MAIN: "main",
  LOGS: "logs"
});

export const LEGACY_BASE_MODULES = Object.freeze([
  "../../app/modules/store.js",
  "../../app/modules/tree-utils.js",
  "../../app/modules/graph-utils.js",
  "../../app/modules/indexing-utils.js",
  "../../app/modules/entry-index-utils.js",
  "../../app/modules/duplicates-utils.js",
  "../../app/modules/import-utils.js",
  "../../app/modules/diagnostics-utils.js",
  "../../app/modules/command-palette-utils.js",
  "../../app/modules/suggestions-utils.js",
  "../../app/modules/auth-utils.js",
  "../../app/modules/autosave-utils.js",
  "../../app/modules/ui-preferences-utils.js",
  "../../app/modules/constants.js",
  "../../app/modules/alias-index.js",
  "../../data/shared/alias/alias_groups.js",
  "../../app/modules/runtime-slots-utils.js",
  "../../app/modules/function-templates-utils.js",
  "../../app/modules/page-namespace-utils.js",
  "../../app/modules/renderer-state-data.js",
  "../../app/modules/dom-utils.js",
  "../../app/modules/universe-graph-utils.js",
  "../../app/modules/universe-state-utils.js",
  "../../app/modules/universe-render-utils.js",
  "../../app/modules/universe-graphics-engine.js",
  "../../data/shared/renderer/group_tokens.js",
  "../../data/shared/renderer/group_paths.js",
  "../../data/shared/renderer/group_specs.js",
  "../../data/shared/renderer/group_sets.js",
  "../../data/shared/renderer/dispatch_specs.js",
  "../../app/modules/math/scalar_math.js",
  "../../app/modules/math/graph_math.js",
  "../../app/modules/math/camera_math.js",
  "../../app/modules/math/projection_math.js",
  "../../app/modules/renderer_dispatch_domain.js",
  "../../app/modules/renderer_universe_domain.js",
  "../../app/modules/renderer_universe_events.js",
  "../../app/modules/renderer_events_domain.js",
  "../../app/modules/renderer_snapshot_domain.js",
  "../../app/modules/renderer_tree_domain.js",
  "../../app/modules/renderer_command_domain.js",
  "../../app/modules/renderer_state_context_domain.js",
  "../../app/modules/renderer_ui_shell_domain.js",
  "../../app/modules/renderer_io_domain.js",
  "../../app/modules/renderer_sentence_domain.js",
  "../../app/modules/renderer_selection_domain.js",
  "../../app/modules/renderer_history_domain.js",
  "../../app/modules/renderer_diagnostics_domain.js",
  "../../app/modules/renderer_statistics_domain.js",
  "../../app/modules/renderer_universe_render_domain.js",
  "../../app/modules/renderer_universe_selection_domain.js",
  "../../app/modules/renderer_runtime_timers_domain.js"
]);

export const LEGACY_SCOPE_ENTRY = Object.freeze({
  [LEGACY_SHELL_SCOPE.MAIN]: "../windows/main_window/legacy_renderer_bridge.js",
  [LEGACY_SHELL_SCOPE.LOGS]: "../windows/logs_window/legacy_logs_bridge.js"
});
