export const LEGACY_SHELL_SCOPE = Object.freeze({
  MAIN: "main",
  LOGS: "logs"
});

export const LEGACY_BASE_MODULES = Object.freeze([
  "../../brain/modules/store.js",
  "../../brain/modules/tree_utils.js",
  "../../brain/modules/graph_utils.js",
  "../../brain/modules/indexing_utils.js",
  "../../brain/modules/entry_index_utils.js",
  "../../brain/modules/duplicates_utils.js",
  "../../brain/modules/import_utils.js",
  "../../brain/modules/diagnostics_utils.js",
  "../../brain/modules/command_palette_utils.js",
  "../../brain/modules/suggestions_utils.js",
  "../../brain/modules/auth_utils.js",
  "../../brain/modules/autosave_utils.js",
  "../../brain/modules/ui_preferences_utils.js",
  "../../brain/modules/constants.js",
  "../../brain/modules/alias_index.js",
  "../../data/input/shared/alias/alias_groups.js",
  "../../brain/modules/runtime_slots_utils.js",
  "../../brain/modules/function_templates_utils.js",
  "../../brain/modules/page_namespace_utils.js",
  "../../brain/modules/renderer_state_data.js",
  "../../brain/modules/dom_utils.js",
  "../../brain/modules/universe_graph_utils.js",
  "../../brain/modules/universe_state_utils.js",
  "../../brain/modules/universe_render_utils.js",
  "../../brain/modules/universe_graphics_engine.js",
  "../../data/input/shared/renderer/group_tokens.js",
  "../../data/input/shared/renderer/group_paths.js",
  "../../data/input/shared/renderer/group_specs.js",
  "../../data/input/shared/renderer/group_sets.js",
  "../../data/input/shared/renderer/dispatch_specs.js",
  "../../brain/math/scalar_math.js",
  "../../brain/math/graph_math.js",
  "../../brain/math/camera_math.js",
  "../../brain/math/projection_math.js",
  "../../brain/wrappers/renderer_dispatch_domain.js",
  "../../brain/wrappers/renderer_universe_domain.js",
  "../../brain/wrappers/renderer_universe_events.js",
  "../../brain/wrappers/renderer_events_domain.js",
  "../../brain/wrappers/renderer_snapshot_domain.js",
  "../../brain/wrappers/renderer_tree_domain.js",
  "../../brain/wrappers/renderer_command_domain.js",
  "../../brain/wrappers/renderer_state_context_domain.js",
  "../../brain/wrappers/renderer_ui_shell_domain.js",
  "../../brain/wrappers/renderer_io_domain.js",
  "../../brain/wrappers/renderer_sentence_domain.js",
  "../../brain/wrappers/renderer_selection_domain.js",
  "../../brain/wrappers/renderer_history_domain.js",
  "../../brain/wrappers/renderer_diagnostics_domain.js",
  "../../brain/wrappers/renderer_statistics_domain.js",
  "../../brain/wrappers/renderer_universe_render_domain.js",
  "../../brain/wrappers/renderer_universe_selection_domain.js",
  "../../brain/wrappers/renderer_runtime_timers_domain.js",
  "../../brain/wrappers/unified_io_wrapper.js"
]);

export const LEGACY_SCOPE_ENTRY = Object.freeze({
  [LEGACY_SHELL_SCOPE.MAIN]: "../windows/main_window/legacy_renderer_bridge.js",
  [LEGACY_SHELL_SCOPE.LOGS]: "../windows/logs_window/legacy_logs_bridge.js"
});

