
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.29531 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/Scripts/"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Launcher/"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/TYmoj/.dotnet/tools/"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/vcpkg/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Program Files/PowerShell/7/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/Users/TYmoj/.lmstudio/bin/"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WinGet/Links/"
      - "C:/Users/TYmoj/AppData/Local/GitHubDesktop/bin/"
      - "C:/Users/TYmoj/AppData/Local/PowerToys/DSCModules/"
      - "C:/Users/TYmoj/AppData/Local/Programs/Antigravity/bin/"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code Insiders/bin/"
    searched_directories:
      - "C:/Windows/System32/ninja-build.com"
      - "C:/Windows/System32/ninja-build.exe"
      - "C:/Windows/System32/ninja-build"
      - "C:/Windows/System32/ninja.com"
      - "C:/Windows/System32/ninja.exe"
      - "C:/Windows/System32/ninja"
      - "C:/Windows/System32/samu.com"
      - "C:/Windows/System32/samu.exe"
      - "C:/Windows/System32/samu"
      - "C:/Windows/ninja-build.com"
      - "C:/Windows/ninja-build.exe"
      - "C:/Windows/ninja-build"
      - "C:/Windows/ninja.com"
      - "C:/Windows/ninja.exe"
      - "C:/Windows/ninja"
      - "C:/Windows/samu.com"
      - "C:/Windows/samu.exe"
      - "C:/Windows/samu"
      - "C:/Windows/System32/wbem/ninja-build.com"
      - "C:/Windows/System32/wbem/ninja-build.exe"
      - "C:/Windows/System32/wbem/ninja-build"
      - "C:/Windows/System32/wbem/ninja.com"
      - "C:/Windows/System32/wbem/ninja.exe"
      - "C:/Windows/System32/wbem/ninja"
      - "C:/Windows/System32/wbem/samu.com"
      - "C:/Windows/System32/wbem/samu.exe"
      - "C:/Windows/System32/wbem/samu"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu"
      - "C:/Windows/System32/OpenSSH/ninja-build.com"
      - "C:/Windows/System32/OpenSSH/ninja-build.exe"
      - "C:/Windows/System32/OpenSSH/ninja-build"
      - "C:/Windows/System32/OpenSSH/ninja.com"
      - "C:/Windows/System32/OpenSSH/ninja.exe"
      - "C:/Windows/System32/OpenSSH/ninja"
      - "C:/Windows/System32/OpenSSH/samu.com"
      - "C:/Windows/System32/OpenSSH/samu.exe"
      - "C:/Windows/System32/OpenSSH/samu"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja-build.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja-build.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja-build"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/samu.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/samu.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/samu"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja-build.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja-build.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja-build"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/samu.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/samu.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/samu"
      - "C:/Program Files/Git/cmd/ninja-build.com"
      - "C:/Program Files/Git/cmd/ninja-build.exe"
      - "C:/Program Files/Git/cmd/ninja-build"
      - "C:/Program Files/Git/cmd/ninja.com"
      - "C:/Program Files/Git/cmd/ninja.exe"
      - "C:/Program Files/Git/cmd/ninja"
      - "C:/Program Files/Git/cmd/samu.com"
      - "C:/Program Files/Git/cmd/samu.exe"
      - "C:/Program Files/Git/cmd/samu"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/Scripts/ninja-build.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/Scripts/ninja-build.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/Scripts/ninja-build"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/Scripts/ninja.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/Scripts/ninja.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/Scripts/ninja"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/Scripts/samu.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/Scripts/samu.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/Scripts/samu"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/ninja-build.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/ninja-build.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/ninja-build"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/ninja.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/ninja.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/ninja"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/samu.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/samu.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Python312/samu"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Launcher/ninja-build.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Launcher/ninja-build.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Launcher/ninja-build"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Launcher/ninja.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Launcher/ninja.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Launcher/ninja"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Launcher/samu.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Launcher/samu.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Python/Launcher/samu"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WindowsApps/ninja-build.com"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WindowsApps/ninja-build.exe"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WindowsApps/ninja-build"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WindowsApps/ninja.com"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WindowsApps/ninja.exe"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WindowsApps/ninja"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WindowsApps/samu.com"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WindowsApps/samu.exe"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WindowsApps/samu"
      - "C:/Users/TYmoj/.dotnet/tools/ninja-build.com"
      - "C:/Users/TYmoj/.dotnet/tools/ninja-build.exe"
      - "C:/Users/TYmoj/.dotnet/tools/ninja-build"
      - "C:/Users/TYmoj/.dotnet/tools/ninja.com"
      - "C:/Users/TYmoj/.dotnet/tools/ninja.exe"
      - "C:/Users/TYmoj/.dotnet/tools/ninja"
      - "C:/Users/TYmoj/.dotnet/tools/samu.com"
      - "C:/Users/TYmoj/.dotnet/tools/samu.exe"
      - "C:/Users/TYmoj/.dotnet/tools/samu"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code/bin/ninja.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code/bin/ninja.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code/bin/ninja"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code/bin/samu.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code/bin/samu.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code/bin/samu"
      - "C:/vcpkg/ninja-build.com"
      - "C:/vcpkg/ninja-build.exe"
      - "C:/vcpkg/ninja-build"
      - "C:/vcpkg/ninja.com"
      - "C:/vcpkg/ninja.exe"
      - "C:/vcpkg/ninja"
      - "C:/vcpkg/samu.com"
      - "C:/vcpkg/samu.exe"
      - "C:/vcpkg/samu"
      - "C:/Program Files/CMake/bin/ninja-build.com"
      - "C:/Program Files/CMake/bin/ninja-build.exe"
      - "C:/Program Files/CMake/bin/ninja-build"
      - "C:/Program Files/CMake/bin/ninja.com"
      - "C:/Program Files/CMake/bin/ninja.exe"
      - "C:/Program Files/CMake/bin/ninja"
      - "C:/Program Files/CMake/bin/samu.com"
      - "C:/Program Files/CMake/bin/samu.exe"
      - "C:/Program Files/CMake/bin/samu"
      - "C:/Program Files/PowerShell/7/ninja-build.com"
      - "C:/Program Files/PowerShell/7/ninja-build.exe"
      - "C:/Program Files/PowerShell/7/ninja-build"
      - "C:/Program Files/PowerShell/7/ninja.com"
      - "C:/Program Files/PowerShell/7/ninja.exe"
      - "C:/Program Files/PowerShell/7/ninja"
      - "C:/Program Files/PowerShell/7/samu.com"
      - "C:/Program Files/PowerShell/7/samu.exe"
      - "C:/Program Files/PowerShell/7/samu"
      - "C:/Program Files/dotnet/ninja-build.com"
      - "C:/Program Files/dotnet/ninja-build.exe"
      - "C:/Program Files/dotnet/ninja-build"
      - "C:/Program Files/dotnet/ninja.com"
      - "C:/Program Files/dotnet/ninja.exe"
      - "C:/Program Files/dotnet/ninja"
      - "C:/Program Files/dotnet/samu.com"
      - "C:/Program Files/dotnet/samu.exe"
      - "C:/Program Files/dotnet/samu"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu"
      - "C:/Users/TYmoj/.lmstudio/bin/ninja-build.com"
      - "C:/Users/TYmoj/.lmstudio/bin/ninja-build.exe"
      - "C:/Users/TYmoj/.lmstudio/bin/ninja-build"
      - "C:/Users/TYmoj/.lmstudio/bin/ninja.com"
      - "C:/Users/TYmoj/.lmstudio/bin/ninja.exe"
      - "C:/Users/TYmoj/.lmstudio/bin/ninja"
      - "C:/Users/TYmoj/.lmstudio/bin/samu.com"
      - "C:/Users/TYmoj/.lmstudio/bin/samu.exe"
      - "C:/Users/TYmoj/.lmstudio/bin/samu"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WinGet/Links/ninja-build.com"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WinGet/Links/ninja-build.exe"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WinGet/Links/ninja-build"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WinGet/Links/ninja.com"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WinGet/Links/ninja.exe"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WinGet/Links/ninja"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WinGet/Links/samu.com"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WinGet/Links/samu.exe"
      - "C:/Users/TYmoj/AppData/Local/Microsoft/WinGet/Links/samu"
      - "C:/Users/TYmoj/AppData/Local/GitHubDesktop/bin/ninja-build.com"
      - "C:/Users/TYmoj/AppData/Local/GitHubDesktop/bin/ninja-build.exe"
      - "C:/Users/TYmoj/AppData/Local/GitHubDesktop/bin/ninja-build"
      - "C:/Users/TYmoj/AppData/Local/GitHubDesktop/bin/ninja.com"
      - "C:/Users/TYmoj/AppData/Local/GitHubDesktop/bin/ninja.exe"
      - "C:/Users/TYmoj/AppData/Local/GitHubDesktop/bin/ninja"
      - "C:/Users/TYmoj/AppData/Local/GitHubDesktop/bin/samu.com"
      - "C:/Users/TYmoj/AppData/Local/GitHubDesktop/bin/samu.exe"
      - "C:/Users/TYmoj/AppData/Local/GitHubDesktop/bin/samu"
      - "C:/Users/TYmoj/AppData/Local/PowerToys/DSCModules/ninja-build.com"
      - "C:/Users/TYmoj/AppData/Local/PowerToys/DSCModules/ninja-build.exe"
      - "C:/Users/TYmoj/AppData/Local/PowerToys/DSCModules/ninja-build"
      - "C:/Users/TYmoj/AppData/Local/PowerToys/DSCModules/ninja.com"
      - "C:/Users/TYmoj/AppData/Local/PowerToys/DSCModules/ninja.exe"
      - "C:/Users/TYmoj/AppData/Local/PowerToys/DSCModules/ninja"
      - "C:/Users/TYmoj/AppData/Local/PowerToys/DSCModules/samu.com"
      - "C:/Users/TYmoj/AppData/Local/PowerToys/DSCModules/samu.exe"
      - "C:/Users/TYmoj/AppData/Local/PowerToys/DSCModules/samu"
      - "C:/Users/TYmoj/AppData/Local/Programs/Antigravity/bin/ninja-build.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Antigravity/bin/ninja-build.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Antigravity/bin/ninja-build"
      - "C:/Users/TYmoj/AppData/Local/Programs/Antigravity/bin/ninja.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Antigravity/bin/ninja.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Antigravity/bin/ninja"
      - "C:/Users/TYmoj/AppData/Local/Programs/Antigravity/bin/samu.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Antigravity/bin/samu.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Antigravity/bin/samu"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code Insiders/bin/ninja-build.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code Insiders/bin/ninja-build.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code Insiders/bin/ninja-build"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code Insiders/bin/ninja.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code Insiders/bin/ninja.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code Insiders/bin/ninja"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code Insiders/bin/samu.com"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code Insiders/bin/samu.exe"
      - "C:/Users/TYmoj/AppData/Local/Programs/Microsoft VS Code Insiders/bin/samu"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Users\\TYmoj\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\"
        - "C:\\Users\\TYmoj\\AppData\\Local\\Programs\\Python\\Python312\\"
        - "C:\\Users\\TYmoj\\AppData\\Local\\Programs\\Python\\Launcher\\"
        - "C:\\Users\\TYmoj\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\TYmoj\\.dotnet\\tools"
        - "C:\\Users\\TYmoj\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\vcpkg"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\PowerShell\\7\\"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Users\\TYmoj\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\"
        - "C:\\Users\\TYmoj\\AppData\\Local\\Programs\\Python\\Python312\\"
        - "C:\\Users\\TYmoj\\AppData\\Local\\Programs\\Python\\Launcher\\"
        - "C:\\Users\\TYmoj\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\TYmoj\\.dotnet\\tools"
        - "C:\\Users\\TYmoj\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\vcpkg"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\PowerShell\\7\\"
        - "C:\\Users\\TYmoj\\.lmstudio\\bin"
        - "C:\\Users\\TYmoj\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\TYmoj\\AppData\\Local\\Microsoft\\WinGet\\Links"
        - "C:\\Users\\TYmoj\\AppData\\Local\\GitHubDesktop\\bin"
        - "C:\\Users\\TYmoj\\AppData\\Local\\PowerToys\\DSCModules\\"
        - "C:\\Users\\TYmoj\\AppData\\Local\\Programs\\Antigravity\\bin"
        - "C:\\Users\\TYmoj\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin"
...
